### ISSUE TITLE
Command system to-do

### ISSUE THREAD

**Issue by Tenrys** [Tenrys/dr-breerb#11]
- [ ] Add "Usage" and/or "Example" fields to help (low priority)
- [ ] Add paging if I go over the number of possible fields (25), though unlikely
- [ ] `CommandContext` object
    - [ ] Argument types, auto resolve
    - [ ] Argument names
    - [ ] Message sending methods, command property on created message
    - ?
- [ ] Turn command availability check into a function

**Comment by Tenrys** [comment]
Redone a lot of the command system, it's already much less of a headache to manage.
