### ISSUE TITLE
Chatsounds to-do

### ISSUE THREAD

**Issue by Tenrys** [Tenrys/dr-breerb#2]
- [ ] Add support for Valve game sounds (https://github.com/PAC3-Server/chatsounds-valve-games, https://www.npmjs.com/package/msgpack)
- [ ] Allow overlapping chatsounds on top of another (https://www.npmjs.com/package/audio-mixer)
- [ ] Play chatsounds one after another, try using the same folder / category for them (prioritize long chatsounds over short ones) (queueing) (THIS WILL BE HARD)
- [ ] Allow assigning channel to playback message as chatsound
- [ ] Audio filters / modifiers (https://github.com/fluent-ffmpeg/node-fluent-ffmpeg)
- [x] Make volume command persist through voice channel connection
- [ ] Allow to search chatsounds by their residing folder / category
